### PR TITLE
Implement the skeleton of CoAP server

### PR DESCRIPTION
**Pull request by 0xDen**
Here is the skeleton of CoAP server.
This code certainly will be expanded.
Please review

### CODE REVIEW

**Comment by macpijan** [comment]
@0xDen @arturkow2000 is implementing client side in Rust. So please guys keep in sync of your work and assign each other for review. Once we have both client and server skeleton/PoC, we can try the first integration test.

**Comment by 0xDen** [comment]
@macpijan @arturkow2000  Okay. Of course it is very raw code and server. I will add more code

File: README [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+plaform provisioning.
+
+As for attestation itself the Fobnail/charra (https://github.com/fobnail/charra)
+project could be used as an example and the base of future extentions.
+It provides a simple (not full) interaction between Attester and Verifier
+over CHARRA protocol.
+
+But local (and remote) provisioning must be performed before the attestation
+starts.
+
```
Comment (arturkow2000) [inline README:12]: Please add instructions on how to build this.
What version of CoAP we need?
App won't build with libcoap from Ubuntu repos (v4.2.1)

```
gcc -Wall -O2 -o fobnail-attester fobnail-attester.c -lcoap-2-tinydtls
fobnail-attester.c:31:13: error: unknown type name ‘coap_request_t’
   31 |       const coap_request_t method, const char* resource_name,
      |             ^~~~~~~~~~~~~~
fobnail-attester.c: In function ‘att_coap_new_context’:
fobnail-attester.c:64:25: warning: implicit declaration of function ‘coap_context_set_block_mode’; did you mean ‘coap_context_get_coap_fd’? [-Wimplicit-function-declaration]
   64 |                         coap_context_set_block_mode(coap_context, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         coap_context_get_coap_fd
fobnail-attester.c:64:67: error: ‘COAP_BLOCK_USE_LIBCOAP’ undeclared (first use in this function)
   64 |                         coap_context_set_block_mode(coap_context, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~
fobnail-attester.c:64:67: note: each undeclared identifier is reported only once for each function it appears in
fobnail-attester.c:64:92: error: ‘COAP_BLOCK_SINGLE_BODY’ undeclared (first use in this function)
   64 |                         coap_context_set_block_mode(coap_context, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
      |                                                                                            ^~~~~~~~~~~~~~~~~~~~~~
fobnail-attester.c: In function ‘main’:
fobnail-attester.c:114:7: warning: implicit declaration of function ‘coap_io_process’ [-Wimplicit-function-declaration]
  114 |   if (coap_io_process(coap_context, COAP_IO_WAIT) == -1) {
      |       ^~~~~~~~~~~~~~~
fobnail-attester.c:114:37: error: ‘COAP_IO_WAIT’ undeclared (first use in this function); did you mean ‘COAP_IO_H_’?
  114 |   if (coap_io_process(coap_context, COAP_IO_WAIT) == -1) {
      |                                     ^~~~~~~~~~~~
      |                                     COAP_IO_H_
make: *** [Makefile:7: all] Error 1
```

File: fobnail-attester.c [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+{
+	quit = true;
+}
+
+static void coap_attest_handler(struct coap_context_t* ctx, struct coap_resource_t* resource,
+				struct coap_session_t* session,	struct coap_pdu_t* in,
+				struct coap_binary_t* token, struct coap_string_t* query,
+				struct coap_pdu_t* out)
+{
+	printf("Received message.\n");
```
Comment (arturkow2000) [inline fobnail-attester.c:27]: Please dump contents of the received message so that we can see what we receive from client.
Also server should send some kind of reply so we can test communication in both ways.

Comment (0xDen) [reply fobnail-attester.c:27]: > Please dump contents of the received message so that we can see what we receive from client.

you mean save in file?

Comment (arturkow2000) [reply fobnail-attester.c:27]: @0xDen print to terminal

**Comment by 0xDen** [comment]
I have run my skeleton program inside docker container which has installed corresponding software (and libcoap2). But currently it seems that there is no such version. I started to work with libcoap v 4.2.x

File: README (hunk 1 above)
Comment (macpijan) [reply README:12]: @arturkow2000 @0xDen Maybe we should add Dockerfile for building/running this application?

**Comment by 0xDen** [comment]
I will create a new PR

**Comment by 0xDen** [comment]
A new PR will be created
